name: FastAPI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ktalk-ai-server:latest

  CD:
    needs: [CI]
    runs-on: ubuntu-20.04

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop ktalk-ai-server || true
            docker rm ktalk-ai-server || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/ktalk-ai-server || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ktalk-ai-server
            docker run -d -p 8000:8000 \
              --name ktalk-ai-server \
              --restart=always \
              ${{ secrets.DOCKERHUB_USERNAME }}/ktalk-ai-server
